### ISSUE TITLE
Replay Console not working as expected

### ISSUE THREAD

**Issue by dbroadhurst** [getsentry/sentry-electron#881]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.22

### Electron Version

25.6

### What platform are you using?

Windows

### Steps to Reproduce

````
import * as Sentry from '@sentry/browser'
import { captureConsoleIntegration } from '@sentry/integrations'

Sentry.init({
  dsn: 'XXXX',
  integrations: [
    captureConsoleIntegration({
      levels: ['log', 'info', 'warn', 'error', 'debug', 'assert']
    }),
    Sentry.replayIntegration({
      maskAllText: false,
      blockAllMedia: false
    })
  ],
  // Session Replay
  replaysSessionSampleRate: 1, // This sets the sample rate at 10%. You may want to change it to 100% while in development and then sample at a lower rate in production.
  replaysOnErrorSampleRate: 1.0 // If you're not already sampling the entire session, change the sample rate to 100% when sampling sessions where errors occur.
})
````

### Expected Result

Expect to see console output in the replay console window

### Actual Result

No console logs appear in the replay console window except when there's an exception.

**Comment by dbroadhurst** [comment]
In addition when I replace 

````
import * as Sentry from '@sentry/browser'
````
with
````
import * as Sentry from '@sentry/electron/renderer'
````

I get the following error. I'm confused which import to use since the docs show both
````
Type 'IntegrationFnResult' is not assignable to type 'Integration'.
  Types of property 'setup' are incompatible.
````

**Comment by timfish** [comment]
> No console logs appear in the replay console window except when there's an exception.

This might be because breadcrumbs aren't collected in the Electron renderer process. I'll look into this!

> Type 'IntegrationFnResult' is not assignable to type 'Integration'.

It sounds like your Sentry dependency versions are mismatched. For v4.22.0 of the Electron SDK, your other Sentry dependencies should all be v7.109.0:
https://github.com/getsentry/sentry-electron/blob/4.22.0/package.json#L58-L62

**Comment by dbroadhurst** [comment]
I got ````import * as Sentry from '@sentry/electron/renderer'```` working by locking the integrations package to 7.109.0. Didn't resolve the console log issue.

**Comment by dbroadhurst** [comment]
@timfish Pulled latest, still not seeing cosole.log  in the replay console window except when an exception happens.

**Comment by timfish** [comment]
The fix has been merged but I haven't cut a release yet. I should get around to doing that tomorrow!

**Comment by timfish** [comment]
Once [this issue](https://github.com/getsentry/publish/issues/3746) has been closed, v4.24.0 will be on npm!

**Comment by dbroadhurst** [comment]
@timfish  Pulled 4.24.0, checked package.json and package-lock.json, still not seeing console.log in the replay console window except when an exception happens.

**Comment by timfish** [comment]
@billyvg has been looking into this and we believe this issues is fixed in the next major version. We're looking into getting this backported but you could [try the beta](https://github.com/getsentry/sentry-electron/releases/tag/5.0.0-beta.0).

**Comment by dbroadhurst** [comment]
Confirmed switching to 5.0.0-beta.0 resolves the console log issue along with some other issues.

btw - captureConsoleIntegration causes to build issue but everything seems to work without this integration
